CONFIG_ZMK_SPLIT=y

# encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# underglow

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
#CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1
# # gold
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=45 
# CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=1
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=0


# display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# the oled display does not draw much power on idle
# CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# sleep and power saving
CONFIG_ZMK_SLEEP=y
#default is 300000
CONFIG_ZMK_IDLE_TIMEOUT=140000
#default is 900000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2000000

# mouse emulation
CONFIG_ZMK_MOUSE=y

# trackpad support
CONFIG_ZMK_POINTING=y
# CONFIG_INPUT_PINNACLE=y

# hardware communication protocols

CONFIG_SPI=y

CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=n

# battery reporting
#CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
#CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

## bluetooth
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7


CONFIG_ZMK_STUDIO=y

# Experimental bluetooth stuff
CONFIG_BT_CTLR_PHY_2M=n
# CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

## logging
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000

# Niceviewgem
# CONFIG_NICE_VIEW_GEM_ANIMATION_MS=26000
CONFIG_NICE_VIEW_GEM_ANIMATION=n